[package]
name = "faster_cp"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }
petgraph = "0.7.1"
special = "0.11.3"
rand = "0.9.0"

[lib]
crate-type = ["cdylib"]